#!/bin/bash

julia -O3 -t 4 Testing_ElectronNuclearDynamics_BinaryIOData.jl > 50x50_Output_Testing_ElectronNuclearDynamics_BinaryIOData.log
julia -O3 -t 4 Testing_ElectronNuclearDynamics_BinaryIOData_ScaleNuclearCoord.jl > 50x50_Output_Testing_ElectronNuclearDynamics_BinaryIOData_ScaleNuclearCoord.log
